name: keep_notes_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_modular: ^6.4.1
  flutter_mobx: ^2.3.0
  mobx: ^2.5.0
  drift: ^2.28.1
  sqlite3_flutter_libs: ^0.5.38
  shared_preferences: ^2.5.3
  flutter_quill: ^11.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.3
  mobx_codegen: ^2.7.1
  drift_dev: ^2.28.0

flutter:
  uses-material-design: true

  assets:
      - assets/images/svg/
      - assets/images/png/

  fonts:
    - family: Nunito
      fonts:
        
        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 300

        - asset: assets/fonts/nunito/Nunito-Regular.ttf
          weight: 400

        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 500

        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700

        - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
          weight: 900

        - asset: assets/fonts/nunito/Nunito-Italic.ttf
          style: italic
